# Generated by Django 5.0 on 2024-04-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
