# Generated by Django 5.0 on 2024-04-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
    ]
