# Generated by Django 5.0 on 2024-04-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_options_user_codeforces_nick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='codeforces_nick',
            new_name='codeforces',
        ),
    ]
