# Generated by Django 5.0 on 2024-04-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_codeforces_nick_user_codeforces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='codeforces',
            new_name='codeforce',
        ),
    ]
