# Generated by Django 5.0 on 2024-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_codeforces_user_codeforce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('time_limit', models.CharField(blank=True, max_length=256, null=True)),
                ('memory_limit', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entry', models.CharField(blank=True, max_length=256, null=True)),
                ('output', models.CharField(blank=True, max_length=256, null=True)),
                ('example_entry', models.CharField(blank=True, max_length=256, null=True)),
                ('example_output', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['id', '-updated'],
            },
        ),
    ]
