# Generated by Django 5.0 on 2024-04-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_competition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['id', '-updated'], 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
    ]
