# Generated by Django 5.0 on 2024-04-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_competition_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.competition'),
        ),
    ]
