# Generated by Django 5.0 on 2024-04-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_organization_competition_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
