# Generated by Django 5.0 on 2024-04-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_competition_date_competition_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='date',
        ),
    ]
