# Generated by Django 5.0 on 2024-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_competition_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
