# Generated by Django 5.0 on 2024-04-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_time_competition_date_competition_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='date',
        ),
    ]
