# Generated by Django 5.0 on 2024-04-16 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_competition_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='participants',
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
