# Generated by Django 5.0 on 2024-04-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_competition_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['start_time'], 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterField(
            model_name='user',
            name='codeforce',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
