# Generated by Django 5.0 on 2024-04-17 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_competition_options_alter_user_codeforce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='competition',
        ),
        migrations.AddField(
            model_name='competition',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tasks'),
        ),
    ]
