# Generated by Django 5.0 on 2024-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_tasks_competition_competition_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='tasks',
        ),
        migrations.AddField(
            model_name='competition',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='base.tasks'),
        ),
    ]
