# Generated by Django 5.0 on 2024-04-17 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.competition'),
        ),
    ]
